#!/usr/bin/env bash
set -e
set -x

export DATABASE_URL=`echo $DATABASE_URL | sed "s/^postgres:\/\//postgresql:\/\//"`

hybridcontents init -l $DATABASE_URL --no-prompt

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user
