#!/usr/bin/env bash
set -e
set -x

export DATABASE_URL=`echo $DATABASE_URL | sed "s/^postgres:\/\//postgresql:\/\//"`

pgcontents init -l $DATABASE_URL --no-prompt

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user

jupyter notebook \
	--no-browser --no-mathjax --ip=0.0.0.0 --port $PORT \
	$JUPYTER_NOTEBOOK_ARGS \
	notebooks
