#!/usr/bin/env bash
set -e
set -x

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user

jupyter notebook \
	--no-browser --no-mathjax --ip=* --port $PORT \
	$JUPYTER_NOTEBOOK_ARGS \
	notebooks
