name: root
dependencies:
  # bind notebook version (compatibility to pgcontents)
  - notebook = 6
  - ipywidgets
  - requests
#  - jupyterlab
  # bind ipython version (compatibility to pgcontents)
  - ipython
  # bind tornado version (websocket problems)
  - tornado
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip = 21
  - pip:
      - hybridcontents
      - pgcontents
      - s3contents
      - jupyterlab
      - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
      - git+git://github.com/quantopian/pgcontents.git